### ISSUE TITLE
Exchange discount trades should pass even if hdx/asset pair does not exists

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/hack.HydraDX-node#13]
Sells/Buys with discounts should go through without the discount if the pair hdx/asset  does not exists.

Currently sell and buys returns error "CannotApplyDiscount" and if this sells is part of the matched transactions , it can lead to scenarion where only part of the amount is trade ( directtrade )

**Comment by jak-pan** [comment]
This should be done as part of #18 ?

**Comment by enthusiastmartin** [comment]
> This should be done as part of #18 ?

Actually, i am not sure now. With the latest refactor and changes - it might be different.

I will verify and test.

**Comment by enthusiastmartin** [comment]
No.

If discount - validation checks if a pool Asset/HDXAsset exists. If not - it returns an error CannotApplyDiscount

If this behavior is still desirable - it might involve little bit more work because we use discount flag to calculate fees as well.
So we would need to put it some way to determine if discount is possible apply ( eg. a helper function which determines if discounts are possible when creating an intenti0on - so it would force set a flag to false if such pool does not exists. )

**Comment by jak-pan** [comment]
Let’s keep this as is then. 

It will change when we update the AMM model.

Jakub Pánik
